# Generated by Django 4.2.4 on 2023-08-29 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RoutesTag",
            new_name="RouteTag",
        ),
    ]
