# Generated by Django 4.2.4 on 2023-08-29 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0004_rename_route_id_routetag_route_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="uploader_id",
            new_name="uploader",
        ),
    ]
