# Generated by Django 4.2.4 on 2023-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0005_rename_uploader_id_route_uploader"),
    ]

    operations = [
        migrations.RenameField(
            model_name="routetag",
            old_name="route",
            new_name="route_id",
        ),
        migrations.RenameField(
            model_name="routetag",
            old_name="tag",
            new_name="tag_id",
        ),
        migrations.AddConstraint(
            model_name="routetag",
            constraint=models.UniqueConstraint(
                models.F("route_id"),
                models.F("tag_id"),
                name="route_tag_unique",
                violation_error_message="Tag already exists for route!",
            ),
        ),
    ]
