# Generated by Django 4.2.4 on 2023-09-06 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0006_rename_route_routetag_route_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="route",
            old_name="uploader",
            new_name="user_id",
        ),
    ]
